cart/urls.py
from django.urls import path

from .views import cart_detail_view, add_to_cart_view, remove_from_cart, clear_cart

app_name= 'cart'

urlpatterns = [
   path('', cart_detail_view, name='cart_detail'),
   path('add/<int:product_id>/', add_to_cart_view, name='cart_add'),
   path('remove/<int:product_id>/', remove_from_cart, name='cart_remove'),
   path('clear/', clear_cart, name='cart_clear'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('accounts/', include('allauth.urls')),
    path('products/', include('products.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('orders.urls')),
    path('payment/', include('payment.urls')),
    

    #rosetta (i18n)
    path('rosetta/', include('rosetta.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from .views import order_create_view

app_name= 'order'
urlpatterns = [
  path('create/', order_create_view, name='order_create'),
]

cart/forms.py
from django import forms

class AddToCartProductForm(forms.Form):
    QUANTITY_CHOICES = [(i, str(i)) for i in range(1,31)]

    quantity = forms.TypedChoiceField(choices=QUANTITY_CHOICES, coerce=int)

    inplace = forms.BooleanField(required=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST
from products.models import Product
from .cart import Cart
from .forms import AddToCartProductForm
from django.contrib import messages
from django.utils.translation import gettext as _

def cart_detail_view(request):
    cart = Cart(request)

    for item in cart:
        item['product_update_quantity_form'] = AddToCartProductForm(initial={
            'quantity': item['quantity'],
            'inplace': True,
        })

    return render(request, 'cart/cart_detail.html', {
        'cart': cart,
        })


@require_POST
def add_to_cart_view(request, product_id):
    cart = Cart(request)

    product = get_object_or_404(Product, id=product_id)
    form = AddToCartProductForm(request.POST)

    if form.is_valid():
        cleaned_data = form.cleaned_data
        quantity = cleaned_data['quantity']
        cart.add(product, quantity, replace_current_quantity=cleaned_data['inplace'])

    return redirect('cart:cart_detail')    

def remove_from_cart(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)

    cart.remove(product)

    return redirect('cart:cart_detail')

@require_POST
def clear_cart(request):
    cart = Cart(request)

    if len(cart):
        cart.clear()
        messages.success(request, _('All products successfully removed from your cart'))
    else:
        messages.warning(request, _('Your cart is already empty'))

    return redirect('product_list')

cart/templates/cart/cart_detail.html
{% extends '_base.html' %}

{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load comment_tags %}
{% load humanize %}

{% load persian_translation_tags %}

{% block content %}
 {% trans "Cart" as x %}
 {% include 'topheader.html' with header_name=x %}

 <!-- Main Content Wrapper Start -->
 <div class="main-content-wrapper">
  <div class="page-content-inner ptb--80">
      <div class="container">
          <div class="row">
              <div class="col-lg-8 mb-md--50">
                      <div class="row no-gutters">
                          <div class="col-12">
                            {% if cart %}
                                <div class="table-content table-responsive">
                                  <table class="table text-center">
                                      <thead>
                                          <tr>
                                              <th></th>
                                              <th>عکس محصول</th>
                                              <th>نام محصول</th>
                                              <th>قیمت</th>
                                              <th>مقدار</th>
                                              <th>مجموع</th>
                                          </tr>
                                      </thead>
                                      <tbody>
                                         {% for item in cart %}
                                          <tr>
                                              <td class="product-remove text-left"><a href="{% url 'cart:cart_remove' item.product_obj.id %}"><i class="flaticon flaticon-cross"></i></a></td>
                                              <td class="product-thumbnail text-left">
                                                  <img src="{{ item.product_obj.cover.url }}">
                                              </td>
                                              <td class="product-name">
                                                  <h3>
                                                      <a href="{{ item.product_obj.get_absolute_url }}">
                                                        {{ item.product_obj.title }}
                                                      </a>
                                                  </h3>
                                              </td>
                                              <td class="product-price">
                                                  <span class="product-price-wrapper">
                                                      <span class="money">{{ item.product_obj.price|intcomma:False|translate_number }}</span>
                                                  </span>
                                              </td>
                                              <td class="product-quantity">
                                                <form class="d-flex" method="Post" action="{% url 'cart:cart_add' item.product_obj.id %}">
                                                    {% csrf_token %}
                                                    <div class="quantity">
                                                        <input
                                                                type="number"
                                                                class="quantity-input"
                                                                name="quantity"
                                                                id="qty-1"
                                                                value="{{ item.quantity }}"
                                                                min="1"
                                                        >                                 
                                                    </div>
                                                     {{ item.product_update_quantity_form.inplace }}
                                                     <button class="small" type="submit"><i class="fa fa-refresh"></i></button>  
                                                </form>
                                              </td>
                                              <td class="product-total-price">
                                                  <span class="product-price-wrapper">
                                                      <span class="money">{{ item.total_price|intcomma:False|translate_number }} {% trans '$' %}</span>
                                                  </span>
                                              </td>
                                          </tr>
                                         {% endfor %}  
                                         
                                      </tbody>
                                  </table>
                              </div>
                            {% else %}
                              <p>{% trans "Cart is Empty! Please add some products to the cart" %}
                              </p>
                              <a href="{% url 'product_list' %}">{% trans "Go shopping" %}
                              </a>
                            {% endif %}
                          </div>
                      </div>
                    {% if not cart.is_empty %}
                        <div class="row no-gutters border-top pt--20 mt--20">
                          <div class="col-sm-6 text-sm-right">
                             <form action="{% url 'cart:cart_clear' %}" method="POST">
                                {% csrf_token %}
                                <button type="submit" class="cart-form__btn">{% trans "Empty Cart" %}</button>  
                             </form>
                          </div>
                        </div>
                    {% endif %}                     
              </div>
              <div class="col-lg-4">
                  <div class="cart-collaterals">
                      <div class="cart-totals">
                          <h5 class="font-size-14 font-bold mb--15">{% trans "Total" %}</h5>
                          <div class="cart-calculator">
                              {% comment %} <div class="cart-calculator__item">
                                  <div class="cart-calculator__item--head">
                                      <span>مجموع</span>
                                  </div>
                                  <div class="cart-calculator__item--value">
                                      <span>۳۴۶,۰۰۰ تومان</span>
                                  </div>
                              </div> {% endcomment %}
                              <div class="cart-calculator__item order-total">
                                  <div class="cart-calculator__item--head">
                                      <span>{% trans "Total_price" %}</span>
                                  </div>
                                  <div class="cart-calculator__item--value">
                                      <span class="product-price-wrapper">
                                          <span class="money">{{ cart.get_total_price|intcomma:False|translate_number }} {% trans '$' %}</span>
                                      </span>
                                  </div>
                              </div>
                          </div>
                      </div>
                      <a href="{% url 'order:order_create' %}" class="btn btn-fullwidth btn-bg-red btn-color-white btn-hover-2">
                          {% trans "Checkout" %}
                      </a>
                  </div>
              </div>
          </div>
      </div>
  </div>
</div>
<!-- Main Content Wrapper Start -->

{% endblock content %}

cart/templates/cart/cart_sidebar.html
{% load i18n %}
{% load humanize %}

{% load persian_translation_tags %}
<!-- Mini Cart Start -->
<aside class="mini-cart" id="miniCart">
  <div class="mini-cart-wrapper">
      <a href="" class="btn-close"><i class="flaticon flaticon-cross"></i></a>
      <div class="mini-cart-inner">
          <h3 class="mini-cart__heading mb--40 mb-lg--30 text-right">{% trans "Cart" %}</h3>
          <div class="mini-cart__content">
              <ul class="mini-cart__list text-right">
                    {% for item in cart %}
                            <li class="mini-cart__product d-flex justify-content-between">
                                <div class="mini-cart__product__image">
                                    <a href="#">
                                            <img src="assets/img/products/prod-1-100x100.jpg">
                                    </a>
                                </div>
                                <div class="mini-cart__product__content pt-2">
                                    <span class="mini-cart__product__title d-flex flex-row justify-content-between">
                                            <a href="#">{{ item.product_obj.title }}</a>
                                            <a href="#" class="">
                                                &#10060;
                                            </a>
                                    </span>
                                    <span class="mini-cart__product__quantity">
                                        <span>{{ item.product_obj.price|intcomma:False|translate_number }} {% trans '$' %}</span> &#215; <span>{{ item.quantity }}</span>
                                    </span>
                                </div>
                            </li>
                {% endfor %}
                  
              </ul>
              <div class="mini-cart__total">
                  <span>{% trans "Total" %}</span>
                  <span class="ammount">{{ cart.get_total_price|intcomma:False|translate_number }} {% trans "$" %}</span>
              </div>
              <div class="mini-cart__buttons">
                  <a href="{% url 'cart:cart_detail' %}" class="btn btn-fullwidth btn-bg-sand mb--20">{% trans "Go to cart" %}</a>
                  {% if not cart.is_empty %}
                       <a href="{% url 'order:order_create' %}" class="btn btn-fullwidth btn-bg-sand">{% trans "checkout" %}</a>
                  {% endif %}
                  
              </div>
          </div>
      </div>
  </div>
</aside>
<!-- Mini Cart End -->